#!/bin/sh
###############################################################################

now=$(date +"%m_%d_%Y")

cd /home/kurt/SmokeScreen/localmedia/server-backup 
mkdir /old/$now &&
mv * /old/$now
cp -R /home/kurt/.config/deluge-anime /home/kurt/SmokeScreen/localmedia/server-backup
cp -R /home/kurt/.config/deluge-movie /home/kurt/SmokeScreen/localmedia/server-backup
cp -R /home/kurt/.config/deluge-music-audio /home/kurt/SmokeScreen/localmedia/server-backup
cp -R /home/kurt/.config/deluge-music-video /home/kurt/SmokeScreen/localmedia/server-backup
cp -R /home/kurt/.config/deluge-tv /home/kurt/SmokeScreen/localmedia/server-backup
cp -R /home/kurt/.config/deluge-uhd-movie /home/kurt/SmokeScreen/localmedia/server-backup
cp -R /home/kurt/.config/deluge-uhd-tv /home/kurt/SmokeScreen/localmedia/server-backup
cp -R /home/kurt/.config/Jackett /home/kurt/SmokeScreen/localmedia/server-backup
cp -R /home/kurt/.config/Lidarr /home/kurt/SmokeScreen/localmedia/server-backup
cp -R /home/kurt/.config/NzbDrone /home/kurt/SmokeScreen/localmedia/server-backup
cp -R /home/kurt/.config/NzbDrone-anime /home/kurt/SmokeScreen/localmedia/server-backup
cp -R /home/kurt/.config/NzbDrone-uhd /home/kurt/SmokeScreen/localmedia/server-backup
cp -R /home/kurt/.config/Radarr /home/kurt/SmokeScreen/localmedia/server-backup
cp -R /home/kurt/.config/rclone /home/kurt/SmokeScreen/localmedia/server-backup
cp -R /home/kurt/.config/SmokeScreen /home/kurt/SmokeScreen/localmedia/server-backup
cp -R /home/kurt/.config/ /home/kurt/SmokeScreen/localmedia/server-backup

exit 0