#!/bin/sh
###############################################################################

now=$(date +"%m_%d_%Y")

cd /home/$USER/Cloud-Accounts/GSUITE/localmedia/Server-Backup 
mkdir /old/$now &&
mv * /old/$now
cp -R /home/$USER/.config/deluge-anime /home/$USER/Cloud-Accounts/GSUITE/localmedia/server-backup
cp -R /home/$USER/.config/deluge-movie /home/$USER/Cloud-Accounts/GSUITE/localmedia/server-backup
cp -R /home/$USER/.config/deluge-music-audio /home/$USER/Cloud-Accounts/GSUITE/localmedia/server-backup
cp -R /home/$USER/.config/deluge-music-video /home/$USER/Cloud-Accounts/GSUITE/localmedia/server-backup
cp -R /home/$USER/.config/deluge-tv /home/$USER/Cloud-Accounts/GSUITE/localmedia/server-backup
cp -R /home/$USER/.config/deluge-uhd-movie /home/$USER/Cloud-Accounts/GSUITE/localmedia/server-backup
cp -R /home/$USER/.config/deluge-uhd-tv /home/$USER/Cloud-Accounts/GSUITE/localmedia/server-backup
cp -R /home/$USER/.config/Jackett /home/$USER/Cloud-Accounts/GSUITE/localmedia/server-backup
cp -R /home/$USER/.config/Lidarr /home/$USER/Cloud-Accounts/GSUITE/localmedia/server-backup
cp -R /home/$USER/.config/NzbDrone /home/$USER/Cloud-Accounts/GSUITE/localmedia/server-backup
cp -R /home/$USER/.config/NzbDrone-anime /home/$USER/Cloud-Accounts/GSUITE/localmedia/server-backup
cp -R /home/$USER/.config/NzbDrone-uhd /home/$USER/Cloud-Accounts/GSUITE/localmedia/server-backup
cp -R /home/$USER/.config/Radarr /home/$USER/Cloud-Accounts/GSUITE/localmedia/server-backup
cp -R /home/$USER/.config/rclone /home/$USER/Cloud-Accounts/GSUITE/localmedia/server-backup
cp -R /home/$USER/.config/SmokeScreen /home/$USER/Cloud-Accounts/GSUITE/localmedia/server-backup
cp -R /home/$USER/.config/ /home/$USER/Cloud-Accounts/GSUITE/localmedia/server-backup

exit 0
